### PR TITLE
prometheus metrics format

### PR DESCRIPTION
**Pull request by pavel987**
This PR adds an alternate display format for data. It's a lot of code that I modified after copy & pasting. I'm not a C developer so I wouldn't be surprised if there's a lot of things wrong with it. Let me know what needs to be fixed/changed to get this merged. Thanks!

### CODE REVIEW

**Comment by nri-pl** [comment]
Hi, Any news about this?

**Comment by SuperQ** [comment]
Have you tested this with [promtoo](https://github.com/prometheus/prometheus/tree/master/cmd/promtool) `check-metrics` mode?

**Comment by nri-pl** [comment]
```
error while linting: text format parsing error in line 37: second HELP line for metric name "nginx_server_requests"
error while linting: text format parsing error in line 37: second TYPE line for metric name "nginx_server_requests", or TYPE reported after samples
...
```

```
# HELP nginx_server_requests requests counter
# TYPE nginx_server_requests counter
nginx_server_requests{code="1xx",host="domain.com"} 0
nginx_server_requests{code="2xx",host="domain.com"} 17
nginx_server_requests{code="3xx",host="domain.com"} 2
nginx_server_requests{code="4xx",host="domain.com"} 3
nginx_server_requests{code="5xx",host="domain.com"} 0
# HELP nginx_server_requests requests counter
# TYPE nginx_server_requests counter
nginx_server_requests{code="1xx",host="_"} 0
nginx_server_requests{code="2xx",host="_"} 1812
nginx_server_requests{code="3xx",host="_"} 0
nginx_server_requests{code="4xx",host="_"} 8
nginx_server_requests{code="5xx",host="_"} 0
# HELP nginx_server_requests requests counter
# TYPE nginx_server_requests counter
nginx_server_requests{code="1xx",host="*"} 0
nginx_server_requests{code="2xx",host="*"} 1829
nginx_server_requests{code="3xx",host="*"} 2
nginx_server_requests{code="4xx",host="*"} 11
nginx_server_requests{code="5xx",host="*"} 0
```

It looks like a small patch would come in handy, but the gun works.
The data appears in the prometheus.

**Comment by vozlt** [comment]
Thanks for the pull request.
I'll check it out soon.

**Comment by vozlt** [comment]
That feature has added.
I have rewritten but it's not much different from yours.
One of the differences is that all mertric names are started with `nginx_vts_(*)`.
I can not guarantee that it will work well because I know little about prometheus.
Please test it.
Thanks.

Latest commit: https://github.com/vozlt/nginx-module-vts/commit/2f9434fc3e3ad60f670a9e1de852bc6230962961

**Comment by pavel987** [comment]
Did a bit of testing and it seems to work well. Do you plan on making a release with these changes anytime soon?

**Comment by vozlt** [comment]
I will release it after checking the histogram in https://github.com/vozlt/nginx-module-vts/issues/62#issuecomment-395451341.
Thanks.

**Comment by vozlt** [comment]
I have tagged the [latest commit](https://github.com/vozlt/nginx-module-vts/commit/ce6111c94c48bbafcd97688112276572ff5463d7) as `v0.1.17`.
Thanks.

**Comment by etlfg** [comment]
Don't know if this is a configuration problem from my side but I have many upstreams behind nginx and I only got one from the /status/format/prometheus. They appear when I use the /status/ or /status/format/json. Any explanation here ?

I didn't create a new issue as It may be an error in your code as you mentioned it.

**Comment by vozlt** [comment]
@etlfg If you still encounter such a problem, please create a new issue.

**Pull request closed without merging**
