### PR TITLE
Release v0.2.0

### PR DESCRIPTION
**Pull request by SuperQ**
Release [v0.2.0] - 2022-09-05
** Bugfix
- fixed for PR[#238](https://github.com/vozlt/nginx-module-vts/issues/238)
- fixed for PR[#238](https://github.com/vozlt/nginx-module-vts/issues/238)
- fixed issues/204 that syntax error has occured
- rollback to 549cc4d
- fixed issues/137, issues/98 that maxSize in cacheZones is displayed incorrectly
- fixed issues/174 that XSS vulnerability in the html page Feature: added moduleVersion field in format/json
- added escape strings for filter names in JSON
- fixed the sum value of histogram in upstream metrics
-  fixed to display all A records of server without zone directive in the upstream block.

** Chore
- Use git-chglog

** Comment
- added moduleVersion
- added additional information about cacheZones
- added tested versions
- added a diagram for the order of module directives

** Compatibility
- fixed ngx_http_vhost_traffic_status_display_get_upstream_nelts() to calculate all A records of server.

** Docs
- Fix README

** Docs
- fix simple typo, destory -> destroy

** Fix
- limit the r->uri search scope to avoid overflow

** Prometheus
- fix nginx_vts_filter_requests_total labels
- remove request "total" metrics

** Refactor
- changed version
- changed spacing
- changed spacing
- changed if statement from merged pull/145

** Test
- describe how to test and fix failed test case

Signed-off-by: SuperQ <superq@gmail.com>

### CODE REVIEW

**Comment by u5surf** [comment]
@SuperQ 
In the README, I've found the version number hard written. What should we do that?
```
## Version
This document describes nginx-module-vts `v0.1.18` released on 22 Jun 2018.
```

**Comment by SuperQ** [comment]
I'll make a link to the Releases page.

**Comment by u5surf** [comment]
@SuperQ LGTM, how about @vozlt ?

**Review by vozlt — COMMENTED** [review]
Thanks for your work.

**Review by u5surf — APPROVED** [review]

**Pull request merged**
