### PR TITLE
Prometheus request count label fixes

### PR DESCRIPTION
**Pull request by robn**
* Remove `code="total"` instances; this is better computed when needed by Prometheus itself
* Fix label naming

### CODE REVIEW

**Comment by Frodox** [comment]
Bump @vozlt

**Comment by dragonfly-net** [comment]
maybe bump other contributors like @SuperQ ?

**Comment by hroost** [comment]
What is the problem with current `code="total"` and benefit of removing?

**Comment by robn** [comment]
Generally, metrics exported to Prometheus should be as raw as possible, and then derivations should be computed by Prometheus as needed.

The normal way to get the total of all variants of a metric is to use `sum(...)`, eg `sum(nginx_vts_filter_requests_total)`. Including the total as another variant with the same name means that any time you want to compute the total, or do more complex queries, you have to ignore or otherwise filter the `code='total'` variant. It's also semantically unclear, as `total` is not actually a valid HTTP request code.

**Comment by SuperQ** [comment]
In addition, `sum(rate(nginx_vts_filter_requests_total[5m]))` would return a double-counted result.

**Pull request merged**
