### PR TITLE
Update ngx_http_vhost_traffic_status_module.c

### PR DESCRIPTION
**Pull request by itpp16**
Prepare code for second 32bit variable which deals with an overflow in stats-in/out bytes, let me know what you think, may have over done it if overflow detection is good in one place, but I found 2 places where in/out is incremented. If you agree or amend the code I can work on the javascript side to add (in = in + in_ov*4.2gb).
A local test shows json (":{"localhost":{"requestCounter":3,"inBytes":1113,"inBytesOv":0,"outBytes":6263,"outBytesOv":0,)
so it looks like it works in principle.

### CODE REVIEW

**Comment by itpp16** [comment]
And then in javascript you do:

                    addov = zone.outBytesOv;
                    if (addov > 0) { addov = addov * 4294967295; }
                    out+=(bTh(zone.outBytes + addov));
                    out+='</td><td>';
                    addov = zone.inBytesOv;
                    if (addov > 0) { addov = addov * 4294967295; }
                    out+=(bTh(zone.inBytes + addov));

it all works :)

**Comment by vozlt** [comment]
Thanks for the patch.
I added that feature.
Please test it.

latest commit: https://github.com/vozlt/nginx-module-vts/commit/e06a618e5780b4b94b21cab37d61820dcd3bb585

**Comment by itpp16** [comment]
After 4.2gb the display goes wrong, lets see if I can add a screendump here.
vhts
My patch does work for servers but something is going wrong for the total (*), still trying to figure that one out, why vtscf is not honoring the struct of ngx_http_vhost_traffic_status_node_t

**Comment by vozlt** [comment]
In latest commint, I added all variables of that is likely to overflow.
My latest commit has a JSON part of "overCounts" as follows:

```JSON
"serverZones":{
    "hostname":{
        "requestCounter":...,
		"inBytes":...,
        "outBytes":...,
		...
        "overCounts":{
            "maxIntegerSize":4294967295,
            "requestCounter":3,
            "inBytes":3,
            "outBytes":3,
            "1xx":0,
            "2xx":0,
            "3xx":0,
            "4xx":0,
            "5xx":3,
            "miss":0,
            "bypass":0,
            "expired":0,
            "stale":0,
            "updating":0,
            "revalidated":0,
            "hit":63,
            "scarce":0
        }
    }
    ...
```
calculation:
`hostname.{object}` + `hostname.overCounts.maxIntegerSize` * `hostname.overCounts.{object}`

calculation examples(requestCounter):
`hostname.requestCounter` + `hostname.overCounts.maxIntegerSize` * `hostname.overCounts.requestCounter`

I wonder whether the overCounts.requestCounter's value is 0. 
Please tell me the content of "overCounts".

**Comment by itpp16** [comment]
I've tried to debug it with ff debugger but can't get those values to show, but I've got a solution for the totals (vtscf), are you aware that vtscf->stats.stat_out_bytes is not consistent with each iteration? a simple debugline "ngx_log_error(NGX_LOG_ALERT, r->connection->log, 0, "d2 var1[%uA]", vtscf->stats.stat_out_bytes);" will show you what I mean. I'm using extern variables (but local to module) for this now and they are consistent with each iteration which is required when your testing for overflows.

**Comment by vozlt** [comment]
You know, your patch and my latest commit is some different.(Is testing code lastest commit?)
I need JSON overCounts's values(or all json) for debugging.
You can obtain using `{yourStatusUri}/format/json`.
You can do it on this wise in ngx_vhost_traffic_status_node_set() to overflow.

```Patch
diff --git a/src/ngx_http_vhost_traffic_status_module.c b/src/ngx_http_vhost_traffic_status_module.c
index 7db0573..c34a1d2 100644
--- a/src/ngx_http_vhost_traffic_status_module.c
+++ b/src/ngx_http_vhost_traffic_status_module.c
@@ -1112,6 +1112,11 @@ static void ngx_vhost_traffic_status_node_set(ngx_http_request_t *r,
     vtsn->stat_in_bytes += (ngx_atomic_uint_t) r->request_length;
     vtsn->stat_out_bytes += (ngx_atomic_uint_t) r->connection->sent;
 
+    /* occur to overflow */
+    vtsn->stat_request_counter += 0xfffffff;
+    vtsn->stat_in_bytes += 0xfffffff;
+    vtsn->stat_out_bytes += 0xfffffff;
+
     ngx_vhost_traffic_status_add_rc(status, vtsn);
 #if (NGX_HTTP_CACHE)
     if (r->upstream != NULL && r->upstream->cache_status != 0) {
```

Please test as above, tell me the result.(JSON)

**Pull request closed without merging**
